global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'broadleaf'
    static_configs:
      - targets: ['site:8080', 'admin:8081', 'api:8082']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
